import type { SimulatorScenario } from '../../types';

export const nurseScenarios: SimulatorScenario[] = [
  {
    id: 'nurse-hypoglycemia-01',
    title: 'Гипогликемия у пациента с СД',
    profession: 'nurse',
    specialty: 'endocrinology',
    specialtyName: 'Эндокринология',
    difficulty: 1,
    description: 'Пациент с сахарным диабетом 2 типа жалуется на слабость и потливость.',
    tags: ['гипогликемия', 'сахарный диабет', 'палатный уход'],
    startStage: 'assessment',
    initialPatient: {
      name: 'Иванов А.П.', age: '62 года', gender: 'male',
      consciousness: 3, consciousnessText: 'Сонливый, отвечает на вопросы',
      vitals: { bp_sys: 130, bp_dia: 80, pulse: 92, spo2: 97, rr: 16, temp: 36.6, pain: 2 },
      skin: 'Бледная, влажная', status: 'warning',
    },
    inventory: ['глюкометр', 'глюкоза 40%', 'сладкий чай', 'тест-полоски', 'журнал наблюдений'],
    stages: {
      assessment: {
        id: 'assessment', title: 'Первичная оценка',
        description: 'Пациент слабый, потеет, жалуется на головокружение. Что делаете в первую очередь?',
        type: 'assessment', timeLimit: 60,
        hint: 'При подозрении на гипогликемию нужно сначала измерить сахар крови.',
        options: [
          { id: 'check-glucose', text: 'Измерить глюкозу крови глюкометром', correct: true,
            score: { assessment: 10, documentation: 5 },
            patientEffect: { status: 'warning' }, nextStage: 'glucose-result',
            feedback: 'Правильно! Измерение глюкозы — ключевой шаг.', log: 'Измерена глюкоза крови' },
          { id: 'give-insulin', text: 'Ввести инсулин', correct: false,
            score: { assessment: 0, action: -10 },
            patientEffect: { pulse: -15, consciousness: -1, status: 'critical' }, nextStage: 'critical-state',
            feedback: 'Ошибка! При гипогликемии инсулин усугубит состояние.', log: 'Ошибочно введён инсулин' },
          { id: 'call-doctor-only', text: 'Позвонить врачу и ждать', correct: false,
            score: { communication: 3, action: -5 },
            patientEffect: { consciousness: -1, status: 'critical' }, nextStage: 'critical-state',
            feedback: 'Недостаточно! Нужно действовать немедленно.', log: 'Вызван врач, действия не предприняты' },
        ],
      },
      'glucose-result': {
        id: 'glucose-result', title: 'Результат: глюкоза 2.8 ммоль/л',
        description: 'Глюкоза критически низкая. Какие действия?',
        type: 'action', timeLimit: 45,
        hint: 'При глюкозе <3.9 нужно дать 15-20г быстрых углеводов.',
        options: [
          { id: 'glucose-iv', text: 'Ввести 40% глюкозу в/в (40-60 мл)', correct: true,
            requires: ['глюкоза 40%'], score: { action: 15, documentation: 5 },
            patientEffect: { consciousness: 1, pulse: -10, status: 'stable' }, nextStage: 'monitoring',
            feedback: 'Отлично! В/в глюкоза — метод выбора.', log: 'Введена 40% глюкоза в/в' },
          { id: 'sweet-tea', text: 'Дать сладкий чай с сахаром', correct: true,
            requires: ['сладкий чай'], score: { action: 10, documentation: 3 },
            patientEffect: { consciousness: 1, status: 'stable' }, nextStage: 'monitoring',
            feedback: 'Хорошо, но при сознании 3 балла есть риск аспирации.', log: 'Дан сладкий чай' },
          { id: 'wait', text: 'Подождать 15 минут', correct: false,
            score: { action: -5 },
            patientEffect: { consciousness: -1, pulse: -10, status: 'critical' }, nextStage: 'critical-state',
            feedback: 'Опасно! Нельзя ждать — нужна немедленная коррекция.', log: 'Принято решение ожидать' },
        ],
      },
      monitoring: {
        id: 'monitoring', title: 'Мониторинг и документация',
        description: 'Состояние стабилизировалось. Что делаете дальше?',
        type: 'documentation', timeLimit: 60,
        options: [
          { id: 'full-doc', text: 'Зафиксировать в журнале все данные', correct: true,
            requires: ['журнал наблюдений'], score: { documentation: 15, communication: 5 },
            patientEffect: { status: 'stable' }, nextStage: 'final-success',
            feedback: 'Отлично! Полная документация — обязательно.', log: 'Внесены записи в журнал' },
          { id: 'notify-doctor', text: 'Сообщить врачу о случае', correct: true,
            score: { communication: 10, documentation: 5 },
            patientEffect: { status: 'stable' }, nextStage: 'final-success',
            feedback: 'Правильно! Врач должен знать.', log: 'Сообщено врачу' },
          { id: 'ignore', text: 'Ничего не документировать', correct: false,
            score: { documentation: -10 },
            patientEffect: { status: 'stable' }, nextStage: 'final-partial',
            feedback: 'Неправильно! Все эпизоды должны быть задокументированы.', log: 'Документация не ведётся' },
        ],
      },
      'critical-state': {
        id: 'critical-state', title: 'Критическое ухудшение',
        description: 'Пациент потерял сознание. Что делаете?',
        type: 'action', timeLimit: 30,
        options: [
          { id: 'emergency-glucose', text: 'Срочно ввести 40% глюкозу в/в и вызвать врача', correct: true,
            requires: ['глюкоза 40%'], score: { action: 15, communication: 10 },
            patientEffect: { consciousness: 2, pulse: 5, status: 'warning' }, nextStage: 'monitoring',
            feedback: 'Правильно! Срочная коррекция + вызов врача.', log: 'Введена 40% глюкоза, вызван врач' },
          { id: 'do-nothing', text: 'Продолжать наблюдение', correct: false,
            score: { action: -15 },
            patientEffect: { consciousness: -1, pulse: -20, status: 'critical' }, nextStage: 'final-death',
            feedback: 'Критическая ошибка! При потере сознания — немедленная помощь.', log: 'Пациент без помощи' },
        ],
      },
      'final-success': { id: 'final-success', title: 'Эпизод завершён', description: 'Гипогликемия купирована.', type: 'documentation', timeLimit: 0, final: true, result: 'success', options: [] },
      'final-partial': { id: 'final-partial', title: 'Эпизод завершён', description: 'Гипогликемия купирована, но документация неполная.', type: 'documentation', timeLimit: 0, final: true, result: 'partial', options: [] },
      'final-death': { id: 'final-death', title: 'Критический исход', description: 'Пациент умер от гипогликемии.', type: 'documentation', timeLimit: 0, final: true, result: 'death', options: [] },
    },
    learningOutcomes: [
      'Признаки гипогликемии: слабость, потливость, головокружение',
      'Первый шаг — измерение глюкозы крови',
      'При глюкозе <3.9 — 15-20г быстрых углеводов или 40% глюкоза в/в',
      'Обязательная документация и уведомление врача',
    ],
  },
];

export default nurseScenarios;
