import type { SimulatorScenario } from '../../types';

export const doctorScenarios: SimulatorScenario[] = [
  {
    id: 'doctor-chest-diff-01',
    title: 'Дифдиагностика: боль в груди',
    profession: 'doctor',
    specialty: 'cardiology',
    specialtyName: 'Кардиология / Терапия',
    difficulty: 3,
    description: 'Пациент 45 лет, острая боль в груди 3 часа, усиливается при вдохе, температура 37.8°C.',
    tags: ['дифференциальная диагностика', 'боль в груди', 'перикардит'],
    startStage: 'anamnesis',
    initialPatient: {
      name: 'Николаев С.П.', age: '45 лет', gender: 'male',
      consciousness: 4, consciousnessText: 'Бодрствует, беспокоен',
      vitals: { bp_sys: 125, bp_dia: 80, pulse: 95, spo2: 96, rr: 20, temp: 37.8, pain: 7 },
      skin: 'Нормальная', status: 'warning',
    },
    inventory: ['ЭКГ', 'тропонин', 'Д-димер', 'рентген ОГК', 'ЭхоКГ', 'КТ-ОГК', 'аспирин', 'гепарин', 'НПВС', 'колхицин', 'анальгетики', 'журнал'],
    stages: {
      anamnesis: {
        id: 'anamnesis', title: 'Сбор анамнеза',
        description: 'Боль в груди 3 часа, усиливается при вдохе, не иррадиирует. Температура 37.8°C. Что спрашиваете?',
        type: 'assessment', timeLimit: 60,
        options: [
          { id: 'detailed-anamnesis', text: 'Уточнить: характер боли, связь с дыханием, ОРВИ, риски ТЭЛА', correct: true,
            score: { assessment: 15, documentation: 5 },
            patientEffect: { status: 'warning' }, nextStage: 'physical-exam',
            feedback: 'Отлично! Колющая боль + связь с вдохом + лихорадка — наводят на перикардит.', log: 'Детальный анамнез собран' },
          { id: 'brief-anamnesis', text: 'Боль в груди → сразу ОКС, назначить аспирин', correct: false,
            score: { assessment: -10, action: -5 },
            patientEffect: { status: 'warning' }, nextStage: 'wrong-treatment',
            feedback: 'Поспешный диагноз! Боль при вдохе + лихорадка — не типично для ОКС.', log: 'Поспешный диагноз ОКС' },
          { id: 'ignore-fever', text: 'Температура — случайность, фокус на сердце', correct: false,
            score: { assessment: -5 },
            patientEffect: { status: 'warning' }, nextStage: 'physical-exam',
            feedback: 'Неправильно! Лихорадка + боль в груди — важный критерий.', log: 'Лихорадка проигнорирована' },
        ],
      },
      'physical-exam': {
        id: 'physical-exam', title: 'Физикальный осмотр',
        description: 'При осмотре: болезненность при пальпации, шум трения перикарда?',
        type: 'assessment', timeLimit: 45,
        options: [
          { id: 'full-exam', text: 'Полный осмотр: перкуссия, аускультация, пальпация, симптомы ТЭЛА', correct: true,
            score: { assessment: 15 },
            patientEffect: { status: 'warning' }, nextStage: 'ecg-choice',
            feedback: 'Правильно! Шум трения + болезненность — аргументы за перикардит.', log: 'Полный физикальный осмотр' },
          { id: 'skip-exam', text: 'Сразу направить на КТ-ОГК', correct: false,
            score: { assessment: -10, action: -5 },
            patientEffect: { status: 'warning' }, nextStage: 'ecg-choice',
            feedback: 'Недостаточно! Физикальный осмотр — обязателен.', log: 'Пропущен физикальный осмотр' },
        ],
      },
      'ecg-choice': {
        id: 'ecg-choice', title: 'ЭКГ: диффузный подъём ST',
        description: 'ЭКГ: диффузный подъём ST во всех отведениях. Что думаете?',
        type: 'decision', timeLimit: 45,
        hint: 'Диффузный ST + болезненность при пальпации + лихорадка = перикардит.',
        options: [
          { id: 'pericarditis-diagnosis', text: 'Острый перикардит: НПВС + колхицин', correct: true,
            score: { assessment: 20, action: 15 },
            patientEffect: { pain: -4, status: 'stable' }, nextStage: 'treatment-monitoring',
            feedback: 'Верно! Диффузный ST + клиника = перикардит. НПВС + колхицин — терапия выбора.', log: 'Диагноз: острый перикардит' },
          { id: 'acs-diagnosis', text: 'ОИМ субэндокардиальный: подъём ST → ПВК', correct: false,
            score: { assessment: -15, action: -10 },
            patientEffect: { pain: 2, status: 'warning' }, nextStage: 'wrong-treatment',
            feedback: 'Ошибка! Диффузный ST без обратной динамики — перикардит, а не ОИМ.', log: 'Ошибочный диагноз ОИМ' },
          { id: 'pe-diagnosis', text: 'ТЭЛА: боль при вдохе → гепарин', correct: false,
            score: { assessment: -10, action: -5 },
            patientEffect: { status: 'warning' }, nextStage: 'wrong-treatment',
            feedback: 'Неправильно! Нет данных за ТЭЛА. Диффузный ST — не ТЭЛА.', log: 'Ошибочный диагноз ТЭЛА' },
        ],
      },
      'treatment-monitoring': {
        id: 'treatment-monitoring', title: 'Лечение и наблюдение',
        description: 'Через 24 часа: боль уменьшилась, температура 37.2°C. Что делаете?',
        type: 'action', timeLimit: 45,
        options: [
          { id: 'continue-protocol', text: 'Продолжить НПВС + колхицин, исключить причину', correct: true,
            score: { action: 15, assessment: 10, documentation: 5 },
            patientEffect: { pain: -2, temp: -0.3, status: 'stable' }, nextStage: 'final-success',
            feedback: 'Отлично! Полный протокол: лечение + поиск этиологии.', log: 'Продолжение терапии' },
          { id: 'discharge', text: 'Выписать — боль же прошла', correct: false,
            score: { action: -15, documentation: -5 },
            patientEffect: { status: 'warning' }, nextStage: 'final-partial',
            feedback: 'Ошибка! Перикардит требует полного курса.', log: 'Ранняя выписка' },
          { id: 'add-antibiotics', text: 'Добавить антибиотики «на всякий случай»', correct: false,
            score: { action: -5, assessment: -5 },
            patientEffect: { status: 'stable' }, nextStage: 'final-partial',
            feedback: 'Неправильно! Антибиотики без подтверждённой инфекции — нерационально.', log: 'Эмпирические антибиотики' },
        ],
      },
      'wrong-treatment': {
        id: 'wrong-treatment', title: 'Осложнение',
        description: 'Пациенту стало хуже. Что делаете?',
        type: 'action', timeLimit: 30,
        options: [
          { id: 're-evaluate', text: 'Отменить предыдущее лечение, пересмотреть диагноз, ЭхоКГ', correct: true,
            score: { assessment: 10, action: 5 },
            patientEffect: { status: 'warning' }, nextStage: 'final-partial',
            feedback: 'Правильно! При ухудшении — пересмотр диагноза.', log: 'Пересмотр диагноза' },
          { id: 'continue-wrong', text: 'Продолжить текущее лечение', correct: false,
            score: { action: -15 },
            patientEffect: { status: 'critical' }, nextStage: 'final-death',
            feedback: 'Критическая ошибка! При ухудшении — немедленный пересмотр.', log: 'Продолжение ошибочного лечения' },
        ],
      },
      'final-success': { id: 'final-success', title: 'Успешное лечение', description: 'Перикардит купирован. Этиология: вирусная.', type: 'documentation', timeLimit: 0, final: true, result: 'success', options: [] },
      'final-partial': { id: 'final-partial', title: 'Лечение с осложнениями', description: 'Диагноз установлен, но с промедлением.', type: 'documentation', timeLimit: 0, final: true, result: 'partial', options: [] },
      'final-death': { id: 'final-death', title: 'Летальный исход', description: 'Осложнения неправильного лечения.', type: 'documentation', timeLimit: 0, final: true, result: 'death', options: [] },
    },
    learningOutcomes: [
      'Дифференциальная диагностика боли в груди: ОКС, ТЭЛА, перикардит',
      'Перикардит: диффузный ST + болезненность при пальпации + лихорадка',
      'НПВС + колхицин — терапия острого перикардита',
      'Обязательный поиск этиологии перикардита',
    ],
  },
];

export default doctorScenarios;
