import type { SimulatorScenario } from '../../types';

export const paramedicScenarios: SimulatorScenario[] = [
  {
    id: 'paramedic-acs-01',
    title: 'ОКС: Боль в груди',
    profession: 'paramedic',
    specialty: 'cardiology',
    specialtyName: 'Кардиология',
    difficulty: 2,
    description: 'Вызов на дом: мужчина 58 лет, острая давящая боль в груди, иррадиирующая в левую руку.',
    tags: ['ОКС', 'боль в груди', 'экстренный вызов'],
    startStage: 'primary-assessment',
    initialPatient: {
      name: 'Сидоров В.К.', age: '58 лет', gender: 'male',
      consciousness: 4, consciousnessText: 'Бодрствует, бледный, потеет',
      vitals: { bp_sys: 160, bp_dia: 95, pulse: 98, spo2: 94, rr: 20, temp: 36.4, pain: 8 },
      skin: 'Бледная, влажная, холодная', status: 'critical',
    },
    inventory: ['ЭКГ', 'оксиметр', 'трофибан', 'морфин', 'аспирин', 'кислород', 'нитроглицерин', 'вейнлок', 'фиксация', 'носилки'],
    stages: {
      'primary-assessment': {
        id: 'primary-assessment', title: 'Первичный осмотр',
        description: 'Пациент с острой болью в груди. Какой первый шаг?',
        type: 'assessment', timeLimit: 60,
        hint: 'При подозрении на ОКС — ЭКГ в течение 10 минут.',
        options: [
          { id: 'ecg-first', text: 'Немедленно сделать ЭКГ (12 отведений)', correct: true,
            requires: ['ЭКГ'], score: { assessment: 20 },
            patientEffect: { status: 'critical' }, nextStage: 'ecg-result',
            feedback: 'Правильно! ЭКГ в течение 10 минут — золотой стандарт.', log: 'ЭКГ 12 отведений выполнена' },
          { id: 'pain-relief-first', text: 'Сначала обезболить (морфин 10 мг в/м)', correct: false,
            score: { action: 5, assessment: -10 },
            patientEffect: { pain: -3, status: 'critical' }, nextStage: 'ecg-result',
            feedback: 'Неправильно! Обезболивание — важно, но ЭКГ имеет приоритет.', log: 'Морфин введён до ЭКГ' },
          { id: 'transport-first', text: 'Немедленно погрузить в машину', correct: false,
            score: { action: -10, assessment: -15 },
            patientEffect: { pulse: 10, bp_sys: 10, status: 'critical' }, nextStage: 'transport-complication',
            feedback: 'Ошибка! Без ЭКГ и стабилизации транспортировка опасна.', log: 'Транспортировка без диагностики' },
        ],
      },
      'ecg-result': {
        id: 'ecg-result', title: 'ЭКГ: подъём ST в V1-V4',
        description: 'ЭКГ показывает ОИМ передней стенки (STEMI). Что делаете?',
        type: 'action', timeLimit: 45,
        hint: 'При STEMI: аспирин, кислород, нитраты, морфин, тикагрелор, вейнлок.',
        options: [
          { id: 'full-protocol', text: 'Аспирин 250 мг + кислород 4-6 л/мин + нитроглицерин 0.5 мг + вейнлок', correct: true,
            requires: ['аспирин', 'кислород', 'нитроглицерин', 'вейнлок'], score: { action: 20, assessment: 5 },
            patientEffect: { spo2: 3, pain: -2, bp_sys: -10, status: 'warning' }, nextStage: 'transport-decision',
            feedback: 'Отлично! Полный протокол стабилизации при STEMI.', log: 'Аспирин, кислород, нитроглицерин, вейнлок' },
          { id: 'aspirin-only', text: 'Дать аспирин и везти в больницу', correct: false,
            score: { action: 5, assessment: -5 },
            patientEffect: { spo2: 1, status: 'critical' }, nextStage: 'transport-complication',
            feedback: 'Недостаточно! При STEMI нужен полный протокол.', log: 'Только аспирин' },
          { id: 'thrombolysis', text: 'Начать тромболиз (алтеплаза) на дому', correct: false,
            score: { action: -15 },
            patientEffect: { pulse: -20, bp_sys: -30, status: 'critical' }, nextStage: 'final-death',
            feedback: 'Категорически запрещено! Тромболиз — только в стационаре.', log: 'Попытка тромболиза на дому' },
        ],
      },
      'transport-decision': {
        id: 'transport-decision', title: 'Решение о транспортировке',
        description: 'Пациент стабилизирован. Куда везти?',
        type: 'decision', timeLimit: 30,
        options: [
          { id: 'pci-center', text: 'Везти в ближайший центр ПВК (<120 мин)', correct: true,
            score: { action: 15, communication: 10 },
            patientEffect: { status: 'stable' }, nextStage: 'final-success',
            feedback: 'Идеально! При STEMI — ПВК в течение 90-120 минут.', log: 'Транспортировка в центр ПВК' },
          { id: 'nearest-hospital', text: 'Везти в ближайшую больницу', correct: false,
            score: { action: -5, communication: -5 },
            patientEffect: { status: 'warning' }, nextStage: 'final-partial',
            feedback: 'Неправильно! При STEMI — только в центр ПВК.', log: 'Транспортировка в ближайшую больницу' },
          { id: 'wait-ambulance', text: 'Ждать кардиореанимацию на месте', correct: false,
            score: { action: -10 },
            patientEffect: { pulse: 10, status: 'critical' }, nextStage: 'transport-complication',
            feedback: 'Неправильно! «Время — мышца». Нужна немедленная транспортировка.', log: 'Ожидание на месте' },
        ],
      },
      'transport-complication': {
        id: 'transport-complication', title: 'Ухудшение при транспортировке',
        description: 'Пульс 40, АД 80/50. Что делаете?',
        type: 'action', timeLimit: 30,
        options: [
          { id: 'atropine-transport', text: 'Атропин 0.5 мг в/в + ускорить транспортировку', correct: true,
            score: { action: 15, communication: 5 },
            patientEffect: { pulse: 20, bp_sys: 20, status: 'warning' }, nextStage: 'final-partial',
            feedback: 'Правильно! Брадикардия при ОКС — атропин + срочная транспортировка.', log: 'Атропин, ускоренная транспортировка' },
          { id: 'cpr', text: 'Начать СЛР', correct: false,
            score: { action: 5, assessment: -5 },
            patientEffect: { pulse: -10, status: 'critical' }, nextStage: 'final-death',
            feedback: 'Преждевременно! При сознании и пульсе СЛР не показана.', log: 'СЛР без показаний' },
        ],
      },
      'final-success': { id: 'final-success', title: 'Успешная стабилизация', description: 'Пациент доставлен в центр ПВК. Время: 95 мин.', type: 'documentation', timeLimit: 0, final: true, result: 'success', options: [] },
      'final-partial': { id: 'final-partial', title: 'Частичный успех', description: 'Доставлен с осложнениями.', type: 'documentation', timeLimit: 0, final: true, result: 'partial', options: [] },
      'final-death': { id: 'final-death', title: 'Летальный исход', description: 'Кардиогенный шок.', type: 'documentation', timeLimit: 0, final: true, result: 'death', options: [] },
    },
    learningOutcomes: [
      'ЭКГ в течение 10 минут при подозрении на ОКС',
      'Протокол MONA: Morphine, Oxygen, Nitrates, Aspirin',
      'При STEMI — транспортировка в центр ПВК <120 мин',
      'Брадикардия при ОКС — атропин 0.5 мг в/в',
    ],
  },
];

export default paramedicScenarios;
